### ISSUE TITLE
Example docker compose does not work

### ISSUE THREAD

**Issue by ankit-sapkota919** [tiredofit/docker-discourse#10]
### Summary

The example docker compose is not working on default.

### Steps to reproduce

Copy the contents of dokcer-compose.yml and run `docker-compose up -d`

### What is the expected *correct* behavior?

The services should start properly and should be accessible locally if mapped at port 3001.

### Relevant logs and/or screenshots

Initially the error on db was `$SUPERUSER_PASSWORD` not set. 
And the discourse image was not able to connect to db.

After that was fixed, the server was unable to start with the following logs:

2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Details
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Lazy YouTube
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Local Dates
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Narrative Bot
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Polls
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Presence
2024-09-26.10:42:53 [NOTICE] ** [discourse] Enabling Plugin: Style Guide
2024-09-26.10:42:53 [INFO] ** [discourse] Migrating Database - This may take a bit..
2024-09-26.10:42:57 [INFO] ** [discourse] Precompiling Assets - This may take a bit..
2024-09-26.10:42:59 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 6.4.0
2024-09-26.10:42:59 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:42:59 [STARTING] ** [scheduling] [1] Starting cron
...
...
...
...
2024-09-26.10:45:30 [STARTING] ** [sidekiq] [45] Starting Sidekiq
2024-09-26.10:45:32 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:33 [STARTING] ** [sidekiq] [46] Starting Sidekiq
2024-09-26.10:45:34 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:36 [STARTING] ** [sidekiq] [47] Starting Sidekiq
2024-09-26.10:45:37 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:40 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:40 [STARTING] ** [sidekiq] [48] Starting Sidekiq
2024-09-26.10:45:43 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:44 [STARTING] ** [sidekiq] [49] Starting Sidekiq
2024-09-26.10:45:45 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
2024-09-26.10:45:47 [STARTING] ** [sidekiq] [50] Starting Sidekiq
2024-09-26.10:45:48 [STARTING] ** [rails] Starting Rails - Discourse version v3.0.2
fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /app
2024-09-26.10:45:50 [ERROR] ** [sidekiq] POTENTIAL RUNWAY DETECTECTED: Disabling 30-sidekiq service because it has tried restarting '50' times

### Environment

- Image version / tag: latest  
- Host OS: Ubuntu 24.04

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

```yml
version: '2.4'
services:
  discourse-app:
    container_name: discourse-app
    image: tiredofit/discourse:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.discourse-example-org.rule=Host(`discourse.example.com`)
      - traefik.http.services.discourse-example-org.loadbalancer.server.port=3000
    volumes:
      - ./logs:/data/logs
      - ./data/uploads:/data/uploads
      - ./data/backups:/data/backups
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-app

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password

      - REDIS_HOST=discourse-redis
      - SITE_HOSTNAME=discourse.example.com

      - SMTP_PORT=25
      - SMTP_HOST=postfix-relay

      - DEVELOPER_EMAILS=hostmaster@example.com
    restart: always
    networks:
      - proxy
      - services

  discourse-db:
    container_name: discourse-db
    image: tiredofit/postgres:15-latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db


      - SUPERUSER_PASS=password
      - POSTGRES_DB=discourse
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=password
    networks:
      - services

  discourse-redis:
    image: tiredofit/redis:7
    container_name: discourse-example-org-redis
    volumes:
      - ./redis:/var/lib/redis
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-redis
    networks:
      - services
    restart: always

  discourse-db-backup:
    image: tiredofit/db-backup
    container_name: discourse-db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db-backup
      - DB_HOST=discourse-db
      - DB_TYPE=postgres
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - services
    restart: always


networks:
  proxy:
    external: true
  services:
    external: true
```
