### ISSUE TITLE
Permission denied @ dir_s_mkdir - /app/public/uploads/default/original

### ISSUE THREAD

**Issue by Khyretos** [tiredofit/docker-discourse#15]
### Summary
cannot change the site logo

### Steps to reproduce
run docker the application, go to Admin > Site Logo and try to change it.

### What is the expected *correct* behavior?
no permission error

### Relevant logs and/or screenshots
there are no logs in portainer that i can share.
![Image](https://github.com/user-attachments/assets/c06b54cc-4e36-4af2-b27d-2c51b9ecffa9)

### Environment
latest docker version as of  14/06/2025

### Possible fixes

My docker compose
```yaml
services:
  discourse-app:
    container_name: discourse-app
    image: tiredofit/discourse:latest
    volumes:
      - ./logs:/data/logs
      - ./data/uploads:/data/uploads
      - ./data/backups:/data/backups
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_NAME=discourse-app

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=[REDACTED]

      - REDIS_HOST=discourse-redis

      - ADMIN_EMAIL=[REDACTED]
      - ADMIN_NAME=[REDACTED]
      - ADMIN_USER=[REDACTED]
      - ADMIN_PASS=[REDACTED]

      - SITE_HOSTNAME=forum.kreative-kompas.com
      - DELIVER_SECURE_ASSETS=TRUE
      
      - SMTP_AUTHENTICATION=login
      - SMTP_DOMAIN=[REDACTED]
      - SMTP_HOST=[REDACTED]
      - SMTP_USER=[REDACTED]
      - SMTP_PASS=T[REDACTED]
      - SMTP_PORT=[REDACTED]

      - DEVELOPER_EMAILS=[REDACTED]
      
#      - PLUGIN_PATH=./plugins
    restart: always
    networks:
      - outside
      - default

  discourse-db:
    container_name: discourse-db
    image: tiredofit/postgres:17
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_NAME=discourse-db

      - SUPERUSER_PASS=[REDACTED]
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=[REDACTED]
    networks:
      - default

  discourse-redis:
    image: tiredofit/redis:7
    container_name: discourse-redis
    #volumes:
    #  - ./redis:/var/lib/redis
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_NAME=discourse-redis
    networks:
      - default
    restart: always

  discourse-db-backup:
    image: tiredofit/db-backup
    container_name: discourse-db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_NAME=discourse-db-backup
      - DB01_HOST=discourse-db
      - DB01_TYPE=postgres
      - DB01_NAME=discourse
      - DB01_USER=discourse
      - DB01_PASS=[REDACTED]
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - default
    restart: always

networks:
  outside:
    external: true
    name: nginx-reverse-proxy_default
```
