### ISSUE TITLE
Less redundant compose file

### ISSUE THREAD

**Issue by frafra** [tiredofit/docker-discourse#7]
**Description of the feature**
Hi!
YAML support anchors, and compose files can use them as well. This, together with defining the `environment` sections as mapping instead of lists, allow having a more compact and less redundant compose file.

**Benefits of feature**

Set the variables just once; more compact and readable compose file.

**Additional context**

Example:
```yaml
version: '2.4'
x-common-environment:
  &default-common-environment
  TIMEZONE: Europe/Oslo
  DB_HOST: discourse-db
  DB_NAME: discourse
  DB_USER: discourse
  DB_PASS: password
services:
  discourse-app:
   image: tiredofit/discourse:latest
    environment:
     << : *default-common-environment
      CONTAINER_NAME: discourse-app
  # ...
  discourse-db-backup:
    image: tiredofit/db-backup
    environment:
      << : *default-common-environment
      CONTAINER_NAME: discourse-db-backup
      DB_TYPE: postgres
      DB_DUMP_FREQ: 1440
      DB_DUMP_BEGIN: 0000
      DB_CLEANUP_TIME: 8640
```
