### ISSUE TITLE
chown: invalid user: 'zabbix:root' & s6-envuidgid: fatal: unknown user: zabbix

### ISSUE THREAD

**Issue by ManjTi** [tiredofit/docker-discourse#8]
### Summary

On starting zabbix agent, error pops up with description: `chown: invalid user: 'zabbix:root'` and other right below `s6-envuidgid: fatal: unknown user: zabbix`

### Steps to reproduce

Build & start container(s) with provided docker-compose file.

### What is the expected *correct* behavior?

Zabbix would start with the correct user 

### Environment

- Image version / tag:  Built on arm64
- Host OS: Rocky Linux

<details>
<summary>Any logs | docker-compose.yml</summary>

```

version: '2.4'
services:
  discourse-app:
    container_name: discourse-app
  #  user: 1000:1000
    image: lld # Built ARM
   # labels:
   #   - traefik.enable=true
   #   - traefik.http.routers.discourse-example-org.rule=Host(`discourse.example.com`)
   #   - traefik.http.services.discourse-example-org.loadbalancer.server.port=3000
    volumes:
      - /home/rocky/server/docker-discourse/examples/logs:/data/logs
      - /home/rocky/server/docker-discourse/examples/data/uploads:/data/uploads
      - /home/rocky/server/docker-discourse/examples/data/backups:/data/backups
    environment:
      - TIMEZONE=Europe/Helsinki
      - CONTAINER_NAME=discourse-app

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password

      - REDIS_HOST=discourse-redis
      - SITE_HOSTNAME=mydomain.com
      - CONTAINER_LOG_LEVEL=DEBUG
      - SMTP_PORT=587
      - SMTP_HOST=postfix-relay
      - SMTP_DOMAIN=mail.smtp2go.com
      - DEVELOPER_EMAILS=mail@mydomain.com
      - PLUGIN_ENABLE_SPOILER_ALERT=TRUE
    restart: always
    networks:
      - nginx
      - services

  discourse-db:
    container_name: discourse-db
  #  user: 1000:1000
    image: postgres:15 # Built ARM
    restart: always
    volumes:
      - /home/rocky/server/docker-discourse/examples/db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=Europe/Helsinki
      - CONTAINER_NAME=discourse-db
      - SUPERUSER_PASS=password

      - POSTGRES_DB=discourse
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=password
    networks:
      - services

  discourse-redis:
    image: tiredofit/redis:7-latest # ARM
  #  user: 1000:1000
    container_name: discourse-example-org-redis
    volumes:
      - /home/rocky/server/docker-discourse/examples/redis:/var/lib/redis
    environment:
      - TIMEZONE=Europe/Helsinki
      - CONTAINER_NAME=discourse-redis
    networks:
      - services
    restart: always

  discourse-db-backup:
    image: tiredofit/db-backup # ARM
   # user: 1000:1000
    container_name: discourse-db-backup
    volumes:
      - /home/rocky/server/docker-discourse/examples/dbbackup:/backup
    environment:
      - TIMEZONE=Europe/Helsinki
      - CONTAINER_NAME=discourse-db-backup
      - DB_HOST=discourse-db
      - DB_TYPE=postgres
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - services
    restart: always


networks:
  nginx:
    external: true
  services:
    external: true


```
</details>
